services:
  - name: maganacademys
    type: web
    runtime: python
    plan: free
   
    buildCommand: './build.sh'
    startCommand: gunicorn elearning.wsgi:application
    # healthCheckPath: /
    # Run DB migrations and collectstatic after each deploy
    postDeploy:
      - python manage.py migrate --noinput
      - python manage.py collectstatic --noinput
